if region == "Antérieure" :
    if not("sarcoidose" || "syphilis" || "sérologie syphilis positive" || "sarcoidose prouvée" || "eruption de zona" || "sérologie tréponémique positive"):
        if oeil == "unilatéral":
            if mode == "aigu":
                if ethnie == "blanc":
                    if genre == "femme":
                        print("Antérieure, exclusion, unilatéral, aigu, blanc, femme")
                    elif genre == "homme":
                        print("Antérieure, exclusion, unilatéral, aigu, blanc, homme")
                elif ethnie == "noir":
                    if genre == "femme":
                        print("Antérieure, exclusion, unilatéral, aigu, noir, femme")
                    elif genre == "homme":
                        print("Antérieure, exclusion, unilatéral, aigu, noir, homme")
                elif ethnie == "asiatique":
                    if genre == "femme":
                        print("Antérieure, exclusion, unilatéral, aigu, asiatique, femme")
                    elif genre == "homme":
                        print("Antérieure, exclusion, unilatéral, aigu, asiatique, homme")
                elif ethnie == "hispanic":
                    if genre == "femme":
                        print("Antérieure, exclusion, unilatéral, aigu, hispanic, femme")
                    elif genre == "homme":
                        print("Antérieure, exclusion, unilatéral, aigu, hispanic, homme")
            elif mode == "récurrent":
                if ethnie == "blanc":
                    if genre == "femme":
                        print("Antérieure, exclusion, unilatéral, récurrent, blanc, femme")
                    elif genre == "homme":
                        print("Antérieure, exclusion, unilatéral, récurrent, blanc, homme")
                elif ethnie == "noir":
                    if genre == "femme":
                        print("Antérieure, exclusion, unilatéral, récurrent, noir, femme")
                    elif genre == "homme":
                        print("Antérieure, exclusion, unilatéral, aigu, blanc, femme"):
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "chronique":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            else:
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
        elif oeil == "à bascule":
            if mode == "aigu":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "récurrent":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "chronique":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            else:
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
        elif oeil == "bilatéral" :
            if mode == "aigu":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "récurrent":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "chronique":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            else:
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
elif region == "Intermédiaire":
    if not ("sérologie syphilis" || "sarcoïdose" || "SEP" || "syphlis"):
        if oeil == "unilatéral":
            if mode == "aigu":
                if ethnie == "blanc":
                    if genre == "femme":
                        print("Intermédiaire, exclusion, unilatéral, aigu, blanc, femme")
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "récurrent":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "chronique":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            else:
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
        elif oeil == "à bascule":
            if mode == "aigu":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "récurrent":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "chronique":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            else:
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
        elif oeil == "bilatéral" :
            if mode == "aigu":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "récurrent":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "chronique":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            else:
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
elif region == "Postérieur":
    if oeil == "unilatéral":
        if mode == "aigu":
            if ethnie == "blanc":
                if genre == "femme":
                    print("Postérieur, unilatéral, aigu, blanc, femme")
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "récurrent":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "chronique":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        else:
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
    elif oeil == "à bascule":
        if mode == "aigu":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "récurrent":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "chronique":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        else:
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
    elif oeil == "bilatéral" :
        if mode == "aigu":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "récurrent":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "chronique":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        else:
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
elif region == "Panuvéite":
    if oeil == "unilatéral":
        if mode == "aigu":
            if ethnie == "blanc":
                if genre == "femme":
                    print("Panuvéite, unilatéral, aigu, blanc, femme")
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "récurrent":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "chronique":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        else:
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
    elif oeil == "à bascule":
        if mode == "aigu":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "récurrent":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "chronique":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        else:
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
    elif oeil == "bilatéral" :
        if mode == "aigu":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "récurrent":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        elif mode == "chronique":
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
        else:
            if ethnie == "blanc":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "noir":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "asiatique":
                if genre == "femme":
                elif genre == "homme":
            elif ethnie == "hispanic":
                if genre == "femme":
                elif genre == "homme":
