region = ""
exclusion=""
oeil=""
mode=""
ethnie=""
genre=""

if region == "Intermédiaire":
    if not ("sérologie syphilis" || "sarcoïdose" || "SEP" || "syphlis"):
        if oeil == "unilatéral":
            if mode == "aigu":
                if ethnie == "blanc":
                    if genre == "femme":
                        print("Intermédiaire, exclusion, unilatéral, aigu, blanc, femme")
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "récurrent":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "chronique":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            else:
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
        elif oeil == "à bascule":
            if mode == "aigu":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "récurrent":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "chronique":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            else:
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
        elif oeil == "bilatéral" :
            if mode == "aigu":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "récurrent":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            elif mode == "chronique":
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":
            else:
                if ethnie == "blanc":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "noir":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "asiatique":
                    if genre == "femme":
                    elif genre == "homme":
                elif ethnie == "hispanic":
                    if genre == "femme":
                    elif genre == "homme":

